/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cloud/model.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud({ opacity = 1, ...props }) {
  const { nodes, materials } = useGLTF('/models/cloud/model.gltf')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mball001.geometry}>
        <meshStandardMaterial
          {...materials['lambert2SG.001']}
          transparent
          opacity={opacity}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/cloud/model.gltf')
